.Dd 01/01/22
.Dt AWF 1
.Os Linux
.Sh NAME
.Nm awf-gtk2
.Nd Application d'aperçu de thème pour GTK 2.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl v
.Op Fl l
.Op Fl n
.Op Fl t Ar theme
.Op Fl s Ar filename
.Op Fl -ltr
.Op Fl -rtl
.Sh DESCRIPTION
La fabrique à widgets est une application d'aperçu de thème pour GTK. Elle
affiche les différents types de widgets fournis par GTK dans une seule
fenêtre permettant de voir l'effet visuel du thème appliqué.
.Bl -tag -width "-s filename"
.It Fl h
Affiche l'aide.
.It Fl v
Affiche le numéro de version.
.It Fl l
Liste les thèmes disponibles.
.It Fl n
Ne démarre pas les spinners.
.It Fl t Ar theme
Démarre avec le thème spécifié.
.It Fl s Ar filename
Démarre et enregistre une capture d'écran png lors du SIGHUP.
.It Fl -ltr
Démarre avec le texte de gauche à droite (Left-To-Right).
.It Fl -rtl
Démarre avec le texte de droite à gauche (Right-To-Left).
.El
.Sh FILES
.Bl -tag -width "/home/user/.awf-gtk-accels" -compact
.It Pa /home/user/.awf-gtk-accels
Configuration des raccourcis clavier.
.El